### ISSUE TITLE
image not transmitting

### ISSUE THREAD

**Issue by helie-q** [spyboy-productions/r4ven#6]
I'm on the website with Brave browser on a redmi note 10 pro. I gave the access to the camera but I don't get the photos. I'm also tunneling it via ngrok. Is that normal ?

**Comment by thisisshubhamkumar** [comment]
please go through the readme file, we have mentioned some browsers like Brave block javascript, try a different browser if the issue isn’t resolved that means there is some problem in the configuration we have also mentioned this in the readme file, If you're not using localhost (http://127.0.0.1:8000) change the URL path in "index.html" on line 203.
