### ISSUE TITLE
option -t is not exist

### ISSUE THREAD

**Issue by bundyboss** [spyboy-productions/r4ven#9]
If I want to use -t option is not working:
 python3 r4ven.py --help
usage: r4ven.py [-p port]

R4VEN - Track device location, and IP address, and capture a photo with device details.

options:
  -h, --help            show this help message and exit
  -p [PORT], --port [PORT]
                        port to listen on

r4ven.py: error: unrecognized arguments: -t

On my android phone picture is not taken but it's working on my lapop.

**Comment by thisisshubhamkumar** [comment]
*Fixed, now -t and -p will work.
using -t you can change the image storing URL if not using localhost.
using -p you can change the port.
